---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, on-prem
summary: Learn what's new with on-prem ONTAP clusters.
---

= What's new with on-prem ONTAP clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new with on-prem ONTAP clusters.

// tag::whats-new[]
== 7 June 2022

The following change was introduced with the 3.9.19 release of the Connector.

=== New Advanced View

If you need to perform advanced management of an ONTAP on-premises cluster, you can do so using ONTAP System Manager, which is a management interface that's provided with an ONTAP system. We have included the System Manager interface directly inside Cloud Manager so that you don't need to leave Cloud Manager for advanced management.

This Advanced View is available as a Preview with on-premises ONTAP clusters running 9.10.0 or later. We plan to refine this experience and add enhancements in upcoming releases. Please send us feedback by using the in-product chat.

link:task-administer-advanced-view.html[Learn more about the Advanced View].

== 27 February 2022

=== An "On-Premises ONTAP" tab is available in the Digital Wallet.

Now you can view an inventory of your on-prem ONTAP clusters along with their hardware and service contracts expiration dates. Additional details about the clusters are also available.

https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html#viewing-cluster-information-and-contract-details[See how to view this important on-prem cluster information]. You'll need to have a NetApp Support Site account (NSS) for the clusters, and the NSS credentials will need to be attached to your Cloud Manager account.

== 11 January 2022

=== Tags that you add to volumes on on-prem ONTAP clusters can be use with the Tagging service.

Tags that you add to a volume are now associated with the  tagging feature of the Application Templates service, which can help you organize and simplify the management of your resources.
// end::whats-new[]

== 28 November 2021

=== Create volume wizard for on-prem ONTAP clusters has been simplified

We redesigned the create volume wizard for ease of use and you can now choose a custom export policy.

== 8 March 2021

=== On-prem ONTAP cluster information available in the Active IQ service

* When Active IQ displays the list of your on-prem clusters (based on your NSS account), you can click a button to link:task-discovering-ontap.html#discovering-clusters-from-the-discovery-page[discover the cluster^] and add it to the Cloud Manager Canvas. This makes it easier to manage all your storage systems from Cloud Manager.

* When Active IQ determines that one or more clusters require firmware updates, you can click a button to link:task-managing-ontap.html#downloading-new-disk-and-shelf-firmware[download the Ansible playbook and upgrade the cluster firmware^].

* A new link:task-managing-ontap.html#viewing-on-prem-workloads-that-are-candidates-for-the-cloud[Cloud-Ready Workloads tab^] provides a list of the workloads or volumes that we have identified as ideal to move to the cloud from your on-prem ONTAP clusters. Moving some of these volumes could reduce your costs and improve performance and resiliency.
+
See link:https://www.netapp.com/knowledge-center/what-is-lift-and-shift[What is Lift and Shift?]
